# Site settings
title: Webjeda Sharebar Demo
tag_text: Webjeda Sharebar Demo
description: A responsive, fast loading, only css share bar for Jekyll websites and blogs.
url: "http://webjeda.com"
baseurl: /webjeda-sharebar

# Build settings
markdown: kramdown

exclude: ["README.md"]
